config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:create]
  end
  namespace :admin do
    resources :restaurants, only: [:index, :edit, :update, :destroy]
  end
  root to: 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
  validates :name, presence: true
  validates :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }, presence: true
  validates :content, presence: true
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
before_action :set_restaurant, only: [:edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to admin_restaurants_path
    else
      render :edit
    end
  end

  def destroy
    @restaurant.delete
    redirect_to admin_restaurants_path
  end

  private

    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end

    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, only: [ :new, :create ]

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render "restaurants/show"
    end
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/restaurants/edit.html.erb
<%= simple_form_for([:admin, @restaurant]) do |f| %>

  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>

  <%= f.button :submit %>
<% end %>

app/views/admin/restaurants/index.html.erb
<h1>Here are all the restaurants</h1>
<%= link_to "Add a restaurant", new_restaurant_path %>

<div class="container">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(-225deg, rgba(255,102,102,0.4) 0%, rgba(255,204,102, 0.4) 50%), url('http://placehold.it/350x150'); background-size: cover;">
          <div class="card-category"><%= restaurant.address %></div>
          <div class="card-description">
            <h2><%= restaurant.name %></h2>
            <p><%= restaurant.phone_number %></p>
            <p><%= restaurant.category %></p>
          </div>
          <%= link_to "#", restaurant_path(restaurant), class: "card-link" %>
        </div>
        <%= link_to "Edit restaurant", edit_admin_restaurant_path(restaurant) %>
      <%= link_to 'Destroy restaurant', admin_restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="wrapper-footer">
  <div class="footer-items">
    <ul class="list-inline">
      <li><i class="fa fa-youtube" aria-hidden="true"></i></li>
      <li><i class="fa fa-instagram" aria-hidden="true"></i></li>
      <li><i class="fa fa-facebook" aria-hidden="true"></i></li>
      <li><i class="fa fa-twitter" aria-hidden="true"></i></li>
    </ul>
    <p>Meilleur site de resto !!</p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <i class="fa fa-cutlery" aria-hidden="true" style="font-size: 30px; color: gold"></i>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Notification -->
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application' %>
  </head>

  <body>
    <%= render "/layouts/navbar" %>
    <%= yield %>
    <%= render "/layouts/footer" %>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Here are all the restaurants</h1>
<%= link_to "Add a restaurant", new_restaurant_path %>
<%= link_to "Admin view", admin_restaurants_path %>
<div class="container">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(-225deg, rgba(255,102,102,0.4) 0%, rgba(255,204,102, 0.4) 50%), url('http://placehold.it/350x150'); background-size: cover;">
          <div class="card-category"><%= restaurant.address %></div>
          <div class="card-description">
            <h2><%= restaurant.name %></h2>
            <p><%= restaurant.phone_number %></p>
            <p><%= restaurant.category %></p>
          </div>
          <%= link_to "#", restaurant_path(restaurant), class: "card-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>

  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>

  <%= f.button :submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category.capitalize %></p>
<h2>Reviews</h2>
<% @restaurant.reviews.each do |review| %>
  <p>Note : <%= "*" * review.rating %> ; Review: <%= review.content %></p>
<% end %>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: (0..5) %>
  <%= f.button :submit %>
<% end %>

<%= link_to "Back to index", restaurants_path %>